name: Bot Codere Aviator

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: |
          npm install playwright playwright-extra puppeteer-extra-plugin-stealth @supabase/supabase-js
          npx playwright install --with-deps chromium

      - name: Ejecutar Bot
        env:
          AUTH_JSON_BASE64: ${{ secrets.AUTH_JSON_BASE64 }}
          GAME_URL: ${{ secrets.GAME_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node bot_cloude.js

      - name: Guardar capturas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capturas
          path: |
            error.png
            inicio_ok.png
